######################## default configuration ####################
baseURL = "https://fergusbarratt.github.io"
title = "TyTN.ai"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # disable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45


############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

#[[menu.main]]
#name = "About"
#URL = "about/"
#weight = 2

#[[menu.main]]
#name = "Blog"
#URL = "blog/"
#weight = 3

[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 2

[[menu.main]]
name = "TinyTN"
URL = "tinytn/"
weight = 3

[[menu.main]]
name = "About us"
URL = "about/"
weight = 4

# only desktop menu
[[menu.desktop]]
name = "Contact"
URL = "contact/"
weight = 1

[[menu.desktop]]
name = "TinyTN"
URL = "tinytn/"
weight = 2

[[menu.desktop]]
name = "About us"
URL = "about/"
weight = 3


#################### default parameters ################################
[params]
# Meta data
description = "This is meta description"
author = "Themefisher"

# favicon
[params.favicon]
favicon = "images/2020-landscape-1-2.png"
# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "TyTN.ai"
image = "images/pexels-pixabay-270549.jpg"

[params.about]
fergus_image = "images/fergus_image.jpg"
jamie_image = "images/jamie_image.jpg"
lewis_image = "images/lewis_image.jpg"
meryem_image = "images/150.png"
fergus_content = "PhD"


# blog
[params.blog]
enable = false
heading = "Blog"

# call to action
[params.call_to_action]
enable = true
title = "Get started with TyTN today"
content = "TyTN's proprietary AI compression pipeline is available today. Contact us to see how we can work with you to deliver radically more efficient deep learning models."
button_label = "Contact Us"
button_url = "contact/"

# gallery
[params.gallery]
enable = false

[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "About Us"
content = "AI compression inspired by quantum mechanics research"
address = "123 Main Street <br> New York, NY 10001"
#hours = ""
#copyright = "Copyright &copy; 2021 a hugo theme by [themefisher](https://themefisher.com/hugo-themes/) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"

############################# social site ########################
[params.social]
#github = '#'
#yelp = "#"
#facebook = "#"
#twitter = "#"
#instagram = "#"
#email = "mailto:tytn.uk@gmail.com"
#linkedin = "#"
